version: '3.4'

services:
  productsdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  basketdb:
    image: redis:alpine

  discountdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  shoppinggateway:
    image: ${DOCKER_REGISTRY-}shoppinggateway
    build:
      context: .
      dockerfile: ApiGateways/ShoppingGateway/Dockerfile

  discount.minapi:
    image: ${DOCKER_REGISTRY-}discountminapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.minAPI/Dockerfile

  products.aggregator:
    image: ${DOCKER_REGISTRY-}productsaggregator
    build:
      context: .
      dockerfile: ApiGateways/Products.Aggregator/Dockerfile

volumes:
  products_mssqldata:
  discount_mssqldata:
