version: '3.4'

services:
  productsdb:
    container_name: productsdb
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes: 
      - products_mssqldata:/var/opt/mssql

  discountdb:
    container_name: discountdb
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"
    volumes: 
      - discount_mssqldata:/var/opt/mssql

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  identitydb:
    container_name: identitydb
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1436:1433"
    volumes: 
      - identity_mssqldata:/var/opt/mssql

  inventorydb:
    container_name: inventorydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=InventoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProductsConnectionString=Server=productsdb;Database=ProductsDb;User Id=sa;Password=aDmin1234!;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - productsdb
      - rabbitmq
    ports:
      - "8001:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUri=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountConnectionString=Server=discountdb;Database=DiscountDb;User Id=sa;Password=aDmin1234!;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  discount.minapi:
    container_name: discount.minapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountConnectionString=Server=discountdb;Database=DiscountDb;User Id=sa;Password=aDmin1234!;"
    depends_on:
      - discountdb
    ports:
      - "8004:80"

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnection=Server=identitydb;Database=IdentityDb;User Id=sa;Password=aDmin1234!;"
      - "JwtIssuer=http://identity.api"
      - "JwtAudience=http://identity.api"
    depends_on:
      - identitydb
    ports:
      - "8005:80"

  store.gateway:
    container_name: store.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Cors_Url=http://store.gateway"
    depends_on:
      - products.aggregator
      - products.api
      - basket.api
      - identity.api
    ports:
      - "8010:80"

  products.aggregator:
    container_name: products.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:ProductsUrl=http://products.api"
      - "ApiSettings:DiscountUrl=http://discount.minapi"
    depends_on:
      - products.api
      - discount.minapi
    ports:
      - "8015:80"

  marketing.gateway:
    container_name: marketing.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discount.minapi
      - products.api
      - products.aggregator
    ports:
      - "8011:80"

  admin.gateway:
    container_name: admin.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - products.api
      - products.aggregator
    ports:
      - "8012:80"
