version: '3.4'

services:
  mssqldata:
    container_name: mssqldata
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "5433:1433"
    volumes: 
      - fs_mssqldata:/var/opt/mssql

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  inventorydb:
    container_name: inventorydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=InventoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProductsConnectionString=Server=mssqldata;Database=ProductsDb;User Id=sa;Password=aDmin1234!;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUri=http://discount.grpc"
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountConnectionString=Server=mssqldata;Database=DiscountDb;User Id=sa;Password=aDmin1234!;"
    ports:
      - "8003:80"

  discount.minapi:
    container_name: discount.minapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountConnectionString=Server=mssqldata;Database=DiscountDb;User Id=sa;Password=aDmin1234!;"
    ports:
      - "8004:80"

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnection=Server=mssqldata;Database=IdentityDb;User Id=sa;Password=aDmin1234!;"
      - "JwtIssuer=http://identity.api"
      - "JwtAudience=http://identity.api"
    ports:
      - "8005:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrdersConnectionString=Server=mssqldata;Database=OrdersDb;User Id=sa;Password=aDmin1234!;"
      - "ApiSettings:IdentityUri=http://identity.api"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "Stripe:WhSecret=${STRIPE_WHSECRET}"
      - "Stripe:SecretKey=${STRIPE_SECRET_KEY}"
      - "Stripe:PublishableKey=${STRIPE_PUBLISHABLE_KEY}"
    ports:
      - "8006:80"

  inventory.api:
    container_name: inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:InventoryConnectionString=Server=inventorydb;Database=InventoryDb;User Id=admin;Password=admin1234;"
      - "ApiSettings:IdentityUri=http://identity.api"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8007:80"

  products.aggregator:
    container_name: products.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:ProductsUrl=http://products.api"
      - "ApiSettings:DiscountUrl=http://discount.minapi"
    ports:
      - "8015:80"  

  store.gateway:
    container_name: store.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Cors_Url=http://store.gateway"
    ports:
      - "8010:80"

  marketing.gateway:
    container_name: marketing.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8011:80"

  admin.gateway:
    container_name: admin.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8012:80"

volumes:
  fs_mssqldata:
    external: false
  postgres_data:
    external: false
