services:
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  basketdb:
    image: redis:alpine

  inventorydb:
    image: postgres:14-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  seq:
    image: datalust/seq:latest

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
    depends_on:
      - mssqldata
      - rabbitmq

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdb

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    depends_on:
      - mssqldata

  discount.minapi:
    image: ${DOCKER_REGISTRY-}discountminapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.minAPI/Dockerfile
    depends_on:
      - mssqldata
      - discount.grpc

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - mssqldata
      - basketdb

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - mssqldata
      - rabbitmq
      - identity.api

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile
    depends_on:
      - inventorydb
      - rabbitmq
      - identity.api

  products.aggregator:
    image: ${DOCKER_REGISTRY-}productsaggregator
    build:
      context: .
      dockerfile: ApiGateways/Products.Aggregator/Dockerfile
    depends_on:
      - products.api
      - discount.minapi
      - inventory.api

  store.gateway:
    image: ${DOCKER_REGISTRY-}storegateway
    build:
      context: .
      dockerfile: ApiGateways/Store.Gateway/Dockerfile
    depends_on:
      - products.aggregator
      - products.api
      - basket.api
      - identity.api

  marketing.gateway:
    image: ${DOCKER_REGISTRY-}marketinggateway
    build:
      context: .
      dockerfile: ApiGateways/Marketing.Gateway/Dockerfile
    depends_on:
      - discount.minapi
      - products.api
      - products.aggregator

  admin.gateway:
    image: ${DOCKER_REGISTRY-}admingateway
    build:
      context: .
      dockerfile: ApiGateways/Admin.Gateway/Dockerfile
    depends_on:
      - products.api
      - products.aggregator

  applicationstatus:
    image: ${DOCKER_REGISTRY-}applicationstatus
    build:
      context: .
      dockerfile: ClientApps/ApplicationStatus/Dockerfile

  admin.blazorserver:
    image: ${DOCKER_REGISTRY-}adminblazorserver
    profiles: ["clientapps", "admin"]
    build:
      context: .
      dockerfile: ClientApps/Admin.BlazorServer/Dockerfile

  store.blazorwasm:
    image: ${DOCKER_REGISTRY-}storeblazorwasm
    profiles: ["clientapps", "store"]
    build:
      context: .
      dockerfile: ClientApps/Store.BlazorWasm/Dockerfile
