version: '3.4'

services:
  productsdb:
    container_name: productsdb
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes: 
      - mssqldata:/var/opt/mssql

  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProductsConnectionString=Server=productsdb;Database=ProductsDb;User Id=sa;Password=aDmin1234!;"
    depends_on:
      - productsdb
    ports:
      - "8001:80"
