version: '3.4'

services:
  productsdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  basketdb:
    image: redis:alpine

  discountdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  inventorydb:
    image: postgres:14-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  discount.minapi:
    image: ${DOCKER_REGISTRY-}discountminapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.minAPI/Dockerfile

  products.aggregator:
    image: ${DOCKER_REGISTRY-}productsaggregator
    build:
      context: .
      dockerfile: ApiGateways/Products.Aggregator/Dockerfile

  store.gateway:
    image: ${DOCKER_REGISTRY-}storegateway
    build:
      context: .
      dockerfile: ApiGateways/Store.Gateway/Dockerfile

  marketing.gateway:
    image: ${DOCKER_REGISTRY-}marketinggateway
    build:
      context: .
      dockerfile: ApiGateways/Marketing.Gateway/Dockerfile

  admin.gateway:
    image: ${DOCKER_REGISTRY-}admingateway
    build:
      context: .
      dockerfile: ApiGateways/Admin.Gateway/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

volumes:
  products_mssqldata:
  discount_mssqldata:
  identity_mssqldata:
  postgres_data:
