version: '3.4'

services:
  productsdb:
    container_name: productsdb
    environment:
      SA_PASSWORD: "aDmin1234!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes: 
      - mssqldata:/var/opt/mssql

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
