global using Products.API.Contracts;
global using Products.API.Controllers;
global using Products.API.DTOs;
global using Products.API.Helpers;
global using Xunit;
global using FluentAssertions;
global using NSubstitute;
global using NSubstitute.ReturnsExtensions;
global using AutoFixture;